
name: AdminTroll
main: Swourire\AdminTroll\Main
version: 1.2.1
api: 3.9.0
mcpe-protocol: [407, 408, 419, 422]

author: Swourire
commands:
 admintroll:
  description:  Admin Troll on/off.
  usage: "Type /admintroll with nothing after, it'll give you the inventory"
  permission: AdminTroll.command
  default: false

 troll:
  description: Invoke a troll
  usage: "Type /troll with nothing after, it'll give you the list of trolls"
  permission: AdminTroll.command
  default: false

permissions:
 AdminTroll:
  description: "Admin Troll default permission"
  default: op
  children:
   AdminTroll.command:
    description: "Admin Troll command permission"
    default: op

 
