
name: AdminTroll
main: Swourire\AdminTroll\Main
version: 1.2.0
api: 3.9.0
mcpe-protocol:
 - 361
 - 362
 - 363
 - 364
 - 365
 - 366
 - 367
 - 368
 - 369
 - 370
 - 371
 - 372
 - 373
 - 374
 - 375
 - 376
 - 377
 - 378
 - 379
 - 380
 - 381
 - 382
 - 383
 - 384
 - 385
 - 386
 - 387
 - 388
 - 389
 - 390
 - 422

author: Swourire
commands:
 admintroll:
  description:  Admin Troll on/off.
  usage: "Type /admintroll with nothing after, it'll give you the inventory"
  permission: AdminTroll.command
  default: false

 troll:
  description: Invoke a troll
  usage: "Type /troll with nothing after, it'll give you the list of trolls"
  permission: AdminTroll.command
  default: false

permissions:
 AdminTroll:
  description: "Admin Troll default permission"
  default: op
  children:
   AdminTroll.command:
    description: "Admin Troll command permission"
    default: op

 
