<?php


namespace Swourire\AdminTroll\Troll\Trolls;


use Swourire\AdminTroll\Troll\TrollBase;

class FakeOp extends TrollBase
{
    protected $name = "FakeOp";
    public function apply(): void
    {
        $this->playerVictim->sendMessage("§7You are now op!");
        parent::apply(); // TODO: Change the autogenerated stub
    }
}