<?php


namespace Swourire\AdminTroll\Troll\Trolls;


use Swourire\AdminTroll\Troll\TrollBase;

class Freeze extends TrollBase
{
    protected $name = "Freezer";
    public function apply(): void
    {
        $player = $this->playerVictim;
        if($player->isImmobile()){
            $player->setImmobile(false);
        }else{
            $player->setImmobile(true);
        }
        parent::apply(); // TODO: Change the autogenerated stub
    }
}