<?php


namespace Swourire\AdminTroll\Troll\Trolls;


use pocketmine\item\Item;
use Swourire\AdminTroll\Troll\TrollBase;

class Pumpkin extends TrollBase
{
    protected $name = "Pumpkiner";
    public function apply(): void
    {
        $pumpkin = Item::get(-155, 0, 1);
        $this->playerVictim->getArmorInventory()->setHelmet($pumpkin);
        parent::apply(); // TODO: Change the autogenerated stub
    }
}