<?php


namespace Swourire\AdminTroll\Troll\Trolls;


use pocketmine\entity\Effect;
use pocketmine\entity\EffectInstance;
use Swourire\AdminTroll\Troll\TrollBase;

class Slow extends TrollBase
{
    protected $name = "Slower";
    public function apply(): void
    {
        $slowness = Effect::getEffect(Effect::SLOWNESS);
        $instance = new EffectInstance($slowness, 2 * 20, 3, false);
        $this->playerVictim->addEffect($instance);
        parent::apply(); // TODO: Change the autogenerated stub
    }

}